model_list: 
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_base: http://127.0.0.1:8000
      api_version: "2024-05-15"
      api_key: os.environ/AZURE_API_KEY 