model_list: 
  - model_name: gpt-4
    litellm_params:
      model: gpt-4
      api_base: http://127.0.0.1:8000
      api_key: random-key
  - model_name: gpt-3.5-turbo
    litellm_params:
        model: gpt-3.5-turbo
        api_key: '${OPENAI_API_KEY}'